server:
  port: 9088

spring:
  mvc:
    servlet:
      load-on-startup: 1

meta-weather-api:
  cityLookup: https://www.metaweather.com/api/location/search/?query={city}
  cityWeather: https://www.metaweather.com/api/location/{woeid}/2018/09/22